### ISSUE TITLE
Does not build today - unrecognized declaration

### ISSUE THREAD

**Issue by quicklisp** [ritschmaster/caveman2-widgets#4]
http://report.quicklisp.org/2016-08-14/failure-report/caveman2-widgets.html#caveman2-widgets has a build log. The fatal warning I get is:

```
; in: DEFUN ADD-AUTHORIZATION
;     (CAVEMAN2-WIDGETS.WIDGET::CIRCLE KEYWORD)
; 
; caught WARNING:
;   unrecognized declaration (CIRCLE KEYWORD)
```

**Comment by ejbs** [comment]
The correct thing to do when declaring types is

(declare (type keyword variable-name))

Your shorthand works for built-in types though (you just accidentally reversed order of the arguments).

**Comment by ritschmaster** [comment]
@ejbs Thank you for your fast reply!

@quicklisp The bug is now fixed.
