### ISSUE TITLE
widget.lisp and widgets.lisp have confusingly similar names

### ISSUE THREAD

**Issue by slyrus** [ritschmaster/caveman2-widgets#6]
Does the project really need two separate files that differ only by singular/pluralness? Seems rather pointless to me.

**Comment by slyrus** [comment]
Not to mention the caveman2-widgets.lisp file. So now, in caveman2, we've got widget.lisp, widgets.lisp, and caveman2-widgets.lisp. No chance for confusion there :)

**Comment by ritschmaster** [comment]
Thanks for your input!

Actually it doesn't and you are right. The widgets.lisp contains only the default widgets. Therefore its name should reproduce that. But as the filename is at the same time the contained package name, I want to keep caveman2-widgets.lisp's name, as it is the interface package to the user/developer.

I am not aware of Common Lisp's state of the art for file names. Maybe my idea is not in line with the thoughts of others, but I welcome other ideas any time!

**Comment by ritschmaster** [comment]
With the newest commit I changed widgets.lisp to default-widgets.lisp: https://github.com/ritschmaster/caveman2-widgets/commit/afe608e915157cb2f3fbe5f7f34fb44d57da7aaa

If that is sufficient for you? Let me know if not!

**Comment by ritschmaster** [comment]
Due inactivity I close this issue. feel free to reopen it.
